# Preface {.unnumbered}

There's a good chance that most people have heard of GDP---the famous or, dare I say, infamous Gross Domestic Product---, which is the yardstick used to measure the economic performance of countries and regions. Fewer people have heard of the System of National Accounts [@systemo2009], which is the underlying methodology to estimate it, along with a myriad of other macroeconomic measurements. Behind that simple number there is information on production, imports, exports, taxes, stock variation and many other aspects of economic life for hundreds of products and putting all that information together is a monumental effort, often carried out by teams of dozens of persons in statistical offices or central banks around the world.

However, all that information is a victim of its own format. The System of National Accounts begins with the production account, which takes the form of two enormous worksheets called supply and use tables---or SUTs in analyst lingo. They hold so much valuable information, but are less effective conveying most of that information effectively just due to their sheer size. If you try to zoom out to fit one of these entire sheets on one screen, the font will be so small that you'll only see a large dark blob on your screen. If you zoom in you'll only be able to view transactions for a few products and economic activities.

From what young people I've trained have told me, and please don't quote me on that, most schools of economics no longer have mandatory courses on National Accounts, which is a shame. I was lucky I still had to estimate Gross and Net National Savings for a final exam back in the early 2000s with pencil and paper. Don't get me wrong, I can see how valuable those classes were now, but I can't say I enjoyed them throughly back then. It was only when I started working on environmental accounts directly using those huge sheets that I really began to understand them from a practical perspective and I began to like them.

My goal with this book is to provide you with that practical understanding of the production account of the System of National Accounts using the data science process. We will use the R programming language to apply those steps, which consist of importing, tidying, transforming, visualizing, and communicating [@wickham2023]. We will leave the modeling part to more competent authors and focus on playing with the data. Along the way, we will use a few cool R packages and, more importantly, a _way_ of doing things. I hope you enjoy it.